version: '3.8'

services:
  db:
    image: postgres:16-alpine
    container_name: terrain_vault_db
    environment:
      POSTGRES_USER: terrain_explorer
      POSTGRES_PASSWORD: supersecretmountainpassword
      POSTGRES_DB: terrain_vault_dev
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
